<tr>
    <td>active</td>
    <td><i>true</i> - active concepts only (default)<br/>
        <i>false</i> - active and inactive concepts
    </td>
</tr>
<tr>
    <td>format</td>
    <td>
        <i>xml</i><br/>
        <i>tsv</i><br/>
        <i>ditatable</i><br/>
        <i>cntable</i><br/>
        <i>json</i><br/>
        <i>html</i><br/>
    </td>
</tr>
<tr>
    <td>changeset</td>
    <td>{changeset uuid}</td>
</tr>